services:
  - type: web
    name: ciccio-chat
    env: elixir
    plan: free
    buildCommand: mix deps.get --only prod && MIX_ENV=prod mix compile && MIX_ENV=prod mix assets.deploy
    startCommand: MIX_ENV=prod mix phx.server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ciccio-chat-db
          property: connectionString
      - key: PHX_HOST
        value: ciccio-chat.onrender.com

databases:
  - name: ciccio-chat-db
    plan: free